### ISSUE TITLE
Is this package going to be updated for the newest version of R?

### ISSUE THREAD

**Issue by Emman-Lopez-Oso** [keberwein/blscrapeR#34] opened 2022-06-19 19:09 UTC
I'd love to be able to keep using it!

**Comment by JohnsonBrent** [comment] 2022-08-29 22:27
Seconding this comment.  ...And thanks for all you've created here so far!

**Comment by TradingPlacesResearch** [comment] 2022-09-13 14:27
Same. Thanks to the contributors! It’s a great library and I would love to keep using it. Thanks again

**Comment by bpffjl** [comment] 2022-09-13 15:03
Sam here! I love this package, but I can't use it now...

**Comment by JohnsonBrent** [comment] 2022-09-13 18:22
Seeing the chatter on this reminds me... I don't have time this second to update someone else's package to the latest version of R.  But in case it helps, [here's a gist](https://gist.github.com/JohnsonBrent/55be01e630250fccc1d55e2d8b212a01) to download all the blscrapeR functions into a temp directory and load them into memory. After running this script, one ought to be able to reference the functions as if one loaded the original blscrapeR package itself. All credit to [keberwein](https://github.com/keberwein) for this package and functions!

**Comment by keberwein-arcadia** [comment] 2022-09-13 19:07
Can someone give the exact error that is being discussed here? I'm unable to reproduce it on my end.

**Comment by keberwein** [comment] 2022-09-13 19:10
Can someone leave the exact error output that's being discussed here. I just installed the package via devtools on a fresh install of R and I can't reproduce the issue.

**Comment by TradingPlacesResearch** [comment] 2022-09-13 19:14
> Can someone leave the exact error output that's being discussed here. I just installed the package via devtools on a fresh install of R and I can't reproduce the issue.

When I run a script:

```
> library(blscrapeR)
Error in library(blscrapeR) : there is no package called ‘blscrapeR’
```

Then

```
> install.packages("blscrapeR")
Warning in install.packages :
  package ‘blscrapeR’ is not available for this version of R
```

**Comment by keberwein** [comment] 2022-09-13 19:18
@TradingPlacesResearch Try installing directly from GitHub. I think that should work. The package isn't on CRAN ATM.

Let me know if the following works.
```
# Update dependencies
install.packages("rlang")
install.packages("devtools")

devtools::install_github("keberwein/blscrapeR")
```

**Comment by TradingPlacesResearch** [comment] 2022-09-13 19:30
BOOM! Thanks! This was a fresh R install on an M1 Mac, so I’m betting that’s where the problem cropped up. Thanks again!

**Comment by keberwein** [comment] 2022-09-13 19:31
Glad I could help! Been meaning to get this project back on CRAN, just been super-slammed in other areas of life lately!

**Comment by keberwein** [comment] 2022-09-17 18:21
Good news gang, this package is now back on CRAN. I'm closing this issue. I'm hoping to have a couple of minor releases in the coming year. 

If this, or any other package ever disappears from CRAN, remember you can still use the `devtools` package to install directly from Github.

`devtools::install_github("keberwein/blscrapeR")`

Thanks for your support!

**Closed as completed by keberwein** 2022-09-17 18:21 UTC
